### ISSUE TITLE
Can I have a named array of fields?

### ISSUE THREAD

**Issue by drFabio** [Netflix/falcor-router-demo#13]
Hello, I noticed that I can have an array of integers on path set like so>
```javascript
'genrelist[{integers:indices}].titles.push'
```

But there isn't an example for the same using names:

``` javascript
route: "titlesById[{integers:titleIds}]['userRating', 'rating']"
```

Is it possible for having in the example above "userRating" and "rating" as something named?

**Comment by sdesai** [comment]
Yes. That should work as exactly as you've typed it.

Here's a similar example from the [router walkthrough](http://netflix.github.io/falcor/documentation/router.html#walkthrough-building-a-router-for-netflix-like-application)

``route: "titlesById[{integers:titleIds}]['name','year']"``

**Comment by drFabio** [comment]
Thanks.
